---
- name: Perform tasks on localhost
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Run yum update
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install packages (Vim, Curl, Wget, Open-VM-Tools, Git)
      yum:
        name:
          - vim
          - curl
          - wget
          - open-vm-tools
          - git
        state: present

    - name: Install Java 11
      yum:
        name: java-11-openjdk
        state: present

    - name: Modify SELinux configuration
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      become: yes

    - name: Disable firewalld service
      service:
        name: firewalld
        state: stopped
        enabled: no
      become: yes

    - name: Download Jenkins repository
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo
        mode: '0644'
      become: yes

    - name: Import Jenkins GPG key
      rpm_key: 
        key: https://pkg.jenkins.io/redhat/jenkins.io-2023.key
        state: present
      become: yes
    
    - name: Install Jenkins
      yum:
        name: jenkins
        state: present
      become: yes

    - name: Enable Jenkins service
      service:
        name: jenkins
        state: started
        enabled: yes
      become: yes
    
    - name: Install epel-release package
      yum:
        name: epel-release
        state: present
      become: yes

    - name: Read initialAdminPassword file
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_admin_password
    
    - name: Display initialAdminPassword
      debug:
        var: initial_admin_password.stdout

  
